package com.mrliu.generate.pojo;

public class AdminInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_info.id
     *
     * @mbggenerated Wed Dec 26 10:29:37 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_info.username
     *
     * @mbggenerated Wed Dec 26 10:29:37 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_info.password
     *
     * @mbggenerated Wed Dec 26 10:29:37 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_info.admin_email
     *
     * @mbggenerated Wed Dec 26 10:29:37 CST 2018
     */
    private String adminEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_info.admin_phone
     *
     * @mbggenerated Wed Dec 26 10:29:37 CST 2018
     */
    private String adminPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_info.admin_sex
     *
     * @mbggenerated Wed Dec 26 10:29:37 CST 2018
     */
    private String adminSex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_info.id
     *
     * @return the value of t_admin_info.id
     *
     * @mbggenerated Wed Dec 26 10:29:37 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_info.id
     *
     * @param id the value for t_admin_info.id
     *
     * @mbggenerated Wed Dec 26 10:29:37 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_info.username
     *
     * @return the value of t_admin_info.username
     *
     * @mbggenerated Wed Dec 26 10:29:37 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_info.username
     *
     * @param username the value for t_admin_info.username
     *
     * @mbggenerated Wed Dec 26 10:29:37 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_info.password
     *
     * @return the value of t_admin_info.password
     *
     * @mbggenerated Wed Dec 26 10:29:37 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_info.password
     *
     * @param password the value for t_admin_info.password
     *
     * @mbggenerated Wed Dec 26 10:29:37 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_info.admin_email
     *
     * @return the value of t_admin_info.admin_email
     *
     * @mbggenerated Wed Dec 26 10:29:37 CST 2018
     */
    public String getAdminEmail() {
        return adminEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_info.admin_email
     *
     * @param adminEmail the value for t_admin_info.admin_email
     *
     * @mbggenerated Wed Dec 26 10:29:37 CST 2018
     */
    public void setAdminEmail(String adminEmail) {
        this.adminEmail = adminEmail == null ? null : adminEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_info.admin_phone
     *
     * @return the value of t_admin_info.admin_phone
     *
     * @mbggenerated Wed Dec 26 10:29:37 CST 2018
     */
    public String getAdminPhone() {
        return adminPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_info.admin_phone
     *
     * @param adminPhone the value for t_admin_info.admin_phone
     *
     * @mbggenerated Wed Dec 26 10:29:37 CST 2018
     */
    public void setAdminPhone(String adminPhone) {
        this.adminPhone = adminPhone == null ? null : adminPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_info.admin_sex
     *
     * @return the value of t_admin_info.admin_sex
     *
     * @mbggenerated Wed Dec 26 10:29:37 CST 2018
     */
    public String getAdminSex() {
        return adminSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_info.admin_sex
     *
     * @param adminSex the value for t_admin_info.admin_sex
     *
     * @mbggenerated Wed Dec 26 10:29:37 CST 2018
     */
    public void setAdminSex(String adminSex) {
        this.adminSex = adminSex == null ? null : adminSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_info
     *
     * @mbggenerated Wed Dec 26 10:29:37 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", adminEmail=").append(adminEmail);
        sb.append(", adminPhone=").append(adminPhone);
        sb.append(", adminSex=").append(adminSex);
        sb.append("]");
        return sb.toString();
    }
}