package com.mrliu.generate.pojo;

import java.util.Date;

public class Video {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ckplayer_video.video_id
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    private Integer videoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ckplayer_video.video_url
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    private String videoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ckplayer_video.video_pattern
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    private String videoPattern;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ckplayer_video.video_clarity
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    private String videoClarity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ckplayer_video.video_weight
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    private Integer videoWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ckplayer_video.video_name
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    private String videoName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ckplayer_video.video_label
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    private String videoLabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ckplayer_video.video_info
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    private String videoInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ckplayer_video.video_thumbnail
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    private String videoThumbnail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ckplayer_video.video_uptime
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    private Date videoUptime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ckplayer_video.video_type
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    private String videoType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ckplayer_video.playsum
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    private Integer playsum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ckplayer_video.comentsum
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    private Integer comentsum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ckplayer_video.collectsum
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    private Integer collectsum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ckplayer_video.supportsum
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    private Integer supportsum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ckplayer_video.video_id
     *
     * @return the value of t_ckplayer_video.video_id
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public Integer getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ckplayer_video.video_id
     *
     * @param videoId the value for t_ckplayer_video.video_id
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public void setVideoId(Integer videoId) {
        this.videoId = videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ckplayer_video.video_url
     *
     * @return the value of t_ckplayer_video.video_url
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ckplayer_video.video_url
     *
     * @param videoUrl the value for t_ckplayer_video.video_url
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl == null ? null : videoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ckplayer_video.video_pattern
     *
     * @return the value of t_ckplayer_video.video_pattern
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public String getVideoPattern() {
        return videoPattern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ckplayer_video.video_pattern
     *
     * @param videoPattern the value for t_ckplayer_video.video_pattern
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public void setVideoPattern(String videoPattern) {
        this.videoPattern = videoPattern == null ? null : videoPattern.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ckplayer_video.video_clarity
     *
     * @return the value of t_ckplayer_video.video_clarity
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public String getVideoClarity() {
        return videoClarity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ckplayer_video.video_clarity
     *
     * @param videoClarity the value for t_ckplayer_video.video_clarity
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public void setVideoClarity(String videoClarity) {
        this.videoClarity = videoClarity == null ? null : videoClarity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ckplayer_video.video_weight
     *
     * @return the value of t_ckplayer_video.video_weight
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public Integer getVideoWeight() {
        return videoWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ckplayer_video.video_weight
     *
     * @param videoWeight the value for t_ckplayer_video.video_weight
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public void setVideoWeight(Integer videoWeight) {
        this.videoWeight = videoWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ckplayer_video.video_name
     *
     * @return the value of t_ckplayer_video.video_name
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public String getVideoName() {
        return videoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ckplayer_video.video_name
     *
     * @param videoName the value for t_ckplayer_video.video_name
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public void setVideoName(String videoName) {
        this.videoName = videoName == null ? null : videoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ckplayer_video.video_label
     *
     * @return the value of t_ckplayer_video.video_label
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public String getVideoLabel() {
        return videoLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ckplayer_video.video_label
     *
     * @param videoLabel the value for t_ckplayer_video.video_label
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public void setVideoLabel(String videoLabel) {
        this.videoLabel = videoLabel == null ? null : videoLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ckplayer_video.video_info
     *
     * @return the value of t_ckplayer_video.video_info
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public String getVideoInfo() {
        return videoInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ckplayer_video.video_info
     *
     * @param videoInfo the value for t_ckplayer_video.video_info
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public void setVideoInfo(String videoInfo) {
        this.videoInfo = videoInfo == null ? null : videoInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ckplayer_video.video_thumbnail
     *
     * @return the value of t_ckplayer_video.video_thumbnail
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public String getVideoThumbnail() {
        return videoThumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ckplayer_video.video_thumbnail
     *
     * @param videoThumbnail the value for t_ckplayer_video.video_thumbnail
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public void setVideoThumbnail(String videoThumbnail) {
        this.videoThumbnail = videoThumbnail == null ? null : videoThumbnail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ckplayer_video.video_uptime
     *
     * @return the value of t_ckplayer_video.video_uptime
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public Date getVideoUptime() {
        return videoUptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ckplayer_video.video_uptime
     *
     * @param videoUptime the value for t_ckplayer_video.video_uptime
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public void setVideoUptime(Date videoUptime) {
        this.videoUptime = videoUptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ckplayer_video.video_type
     *
     * @return the value of t_ckplayer_video.video_type
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public String getVideoType() {
        return videoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ckplayer_video.video_type
     *
     * @param videoType the value for t_ckplayer_video.video_type
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public void setVideoType(String videoType) {
        this.videoType = videoType == null ? null : videoType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ckplayer_video.playsum
     *
     * @return the value of t_ckplayer_video.playsum
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public Integer getPlaysum() {
        return playsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ckplayer_video.playsum
     *
     * @param playsum the value for t_ckplayer_video.playsum
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public void setPlaysum(Integer playsum) {
        this.playsum = playsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ckplayer_video.comentsum
     *
     * @return the value of t_ckplayer_video.comentsum
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public Integer getComentsum() {
        return comentsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ckplayer_video.comentsum
     *
     * @param comentsum the value for t_ckplayer_video.comentsum
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public void setComentsum(Integer comentsum) {
        this.comentsum = comentsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ckplayer_video.collectsum
     *
     * @return the value of t_ckplayer_video.collectsum
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public Integer getCollectsum() {
        return collectsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ckplayer_video.collectsum
     *
     * @param collectsum the value for t_ckplayer_video.collectsum
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public void setCollectsum(Integer collectsum) {
        this.collectsum = collectsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ckplayer_video.supportsum
     *
     * @return the value of t_ckplayer_video.supportsum
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public Integer getSupportsum() {
        return supportsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ckplayer_video.supportsum
     *
     * @param supportsum the value for t_ckplayer_video.supportsum
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public void setSupportsum(Integer supportsum) {
        this.supportsum = supportsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ckplayer_video
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", videoId=").append(videoId);
        sb.append(", videoUrl=").append(videoUrl);
        sb.append(", videoPattern=").append(videoPattern);
        sb.append(", videoClarity=").append(videoClarity);
        sb.append(", videoWeight=").append(videoWeight);
        sb.append(", videoName=").append(videoName);
        sb.append(", videoLabel=").append(videoLabel);
        sb.append(", videoInfo=").append(videoInfo);
        sb.append(", videoThumbnail=").append(videoThumbnail);
        sb.append(", videoUptime=").append(videoUptime);
        sb.append(", videoType=").append(videoType);
        sb.append(", playsum=").append(playsum);
        sb.append(", comentsum=").append(comentsum);
        sb.append(", collectsum=").append(collectsum);
        sb.append(", supportsum=").append(supportsum);
        sb.append("]");
        return sb.toString();
    }
}