package com.mrliu.generate.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class VideoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ckplayer_video
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ckplayer_video
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ckplayer_video
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ckplayer_video
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public VideoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ckplayer_video
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ckplayer_video
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ckplayer_video
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ckplayer_video
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ckplayer_video
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ckplayer_video
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ckplayer_video
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ckplayer_video
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ckplayer_video
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ckplayer_video
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ckplayer_video
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVideoIdIsNull() {
            addCriterion("video_id is null");
            return (Criteria) this;
        }

        public Criteria andVideoIdIsNotNull() {
            addCriterion("video_id is not null");
            return (Criteria) this;
        }

        public Criteria andVideoIdEqualTo(Integer value) {
            addCriterion("video_id =", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdNotEqualTo(Integer value) {
            addCriterion("video_id <>", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdGreaterThan(Integer value) {
            addCriterion("video_id >", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("video_id >=", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdLessThan(Integer value) {
            addCriterion("video_id <", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdLessThanOrEqualTo(Integer value) {
            addCriterion("video_id <=", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdIn(List<Integer> values) {
            addCriterion("video_id in", values, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdNotIn(List<Integer> values) {
            addCriterion("video_id not in", values, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdBetween(Integer value1, Integer value2) {
            addCriterion("video_id between", value1, value2, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdNotBetween(Integer value1, Integer value2) {
            addCriterion("video_id not between", value1, value2, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoUrlIsNull() {
            addCriterion("video_url is null");
            return (Criteria) this;
        }

        public Criteria andVideoUrlIsNotNull() {
            addCriterion("video_url is not null");
            return (Criteria) this;
        }

        public Criteria andVideoUrlEqualTo(String value) {
            addCriterion("video_url =", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlNotEqualTo(String value) {
            addCriterion("video_url <>", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlGreaterThan(String value) {
            addCriterion("video_url >", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlGreaterThanOrEqualTo(String value) {
            addCriterion("video_url >=", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlLessThan(String value) {
            addCriterion("video_url <", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlLessThanOrEqualTo(String value) {
            addCriterion("video_url <=", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlLike(String value) {
            addCriterion("video_url like", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlNotLike(String value) {
            addCriterion("video_url not like", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlIn(List<String> values) {
            addCriterion("video_url in", values, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlNotIn(List<String> values) {
            addCriterion("video_url not in", values, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlBetween(String value1, String value2) {
            addCriterion("video_url between", value1, value2, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlNotBetween(String value1, String value2) {
            addCriterion("video_url not between", value1, value2, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoPatternIsNull() {
            addCriterion("video_pattern is null");
            return (Criteria) this;
        }

        public Criteria andVideoPatternIsNotNull() {
            addCriterion("video_pattern is not null");
            return (Criteria) this;
        }

        public Criteria andVideoPatternEqualTo(String value) {
            addCriterion("video_pattern =", value, "videoPattern");
            return (Criteria) this;
        }

        public Criteria andVideoPatternNotEqualTo(String value) {
            addCriterion("video_pattern <>", value, "videoPattern");
            return (Criteria) this;
        }

        public Criteria andVideoPatternGreaterThan(String value) {
            addCriterion("video_pattern >", value, "videoPattern");
            return (Criteria) this;
        }

        public Criteria andVideoPatternGreaterThanOrEqualTo(String value) {
            addCriterion("video_pattern >=", value, "videoPattern");
            return (Criteria) this;
        }

        public Criteria andVideoPatternLessThan(String value) {
            addCriterion("video_pattern <", value, "videoPattern");
            return (Criteria) this;
        }

        public Criteria andVideoPatternLessThanOrEqualTo(String value) {
            addCriterion("video_pattern <=", value, "videoPattern");
            return (Criteria) this;
        }

        public Criteria andVideoPatternLike(String value) {
            addCriterion("video_pattern like", value, "videoPattern");
            return (Criteria) this;
        }

        public Criteria andVideoPatternNotLike(String value) {
            addCriterion("video_pattern not like", value, "videoPattern");
            return (Criteria) this;
        }

        public Criteria andVideoPatternIn(List<String> values) {
            addCriterion("video_pattern in", values, "videoPattern");
            return (Criteria) this;
        }

        public Criteria andVideoPatternNotIn(List<String> values) {
            addCriterion("video_pattern not in", values, "videoPattern");
            return (Criteria) this;
        }

        public Criteria andVideoPatternBetween(String value1, String value2) {
            addCriterion("video_pattern between", value1, value2, "videoPattern");
            return (Criteria) this;
        }

        public Criteria andVideoPatternNotBetween(String value1, String value2) {
            addCriterion("video_pattern not between", value1, value2, "videoPattern");
            return (Criteria) this;
        }

        public Criteria andVideoClarityIsNull() {
            addCriterion("video_clarity is null");
            return (Criteria) this;
        }

        public Criteria andVideoClarityIsNotNull() {
            addCriterion("video_clarity is not null");
            return (Criteria) this;
        }

        public Criteria andVideoClarityEqualTo(String value) {
            addCriterion("video_clarity =", value, "videoClarity");
            return (Criteria) this;
        }

        public Criteria andVideoClarityNotEqualTo(String value) {
            addCriterion("video_clarity <>", value, "videoClarity");
            return (Criteria) this;
        }

        public Criteria andVideoClarityGreaterThan(String value) {
            addCriterion("video_clarity >", value, "videoClarity");
            return (Criteria) this;
        }

        public Criteria andVideoClarityGreaterThanOrEqualTo(String value) {
            addCriterion("video_clarity >=", value, "videoClarity");
            return (Criteria) this;
        }

        public Criteria andVideoClarityLessThan(String value) {
            addCriterion("video_clarity <", value, "videoClarity");
            return (Criteria) this;
        }

        public Criteria andVideoClarityLessThanOrEqualTo(String value) {
            addCriterion("video_clarity <=", value, "videoClarity");
            return (Criteria) this;
        }

        public Criteria andVideoClarityLike(String value) {
            addCriterion("video_clarity like", value, "videoClarity");
            return (Criteria) this;
        }

        public Criteria andVideoClarityNotLike(String value) {
            addCriterion("video_clarity not like", value, "videoClarity");
            return (Criteria) this;
        }

        public Criteria andVideoClarityIn(List<String> values) {
            addCriterion("video_clarity in", values, "videoClarity");
            return (Criteria) this;
        }

        public Criteria andVideoClarityNotIn(List<String> values) {
            addCriterion("video_clarity not in", values, "videoClarity");
            return (Criteria) this;
        }

        public Criteria andVideoClarityBetween(String value1, String value2) {
            addCriterion("video_clarity between", value1, value2, "videoClarity");
            return (Criteria) this;
        }

        public Criteria andVideoClarityNotBetween(String value1, String value2) {
            addCriterion("video_clarity not between", value1, value2, "videoClarity");
            return (Criteria) this;
        }

        public Criteria andVideoWeightIsNull() {
            addCriterion("video_weight is null");
            return (Criteria) this;
        }

        public Criteria andVideoWeightIsNotNull() {
            addCriterion("video_weight is not null");
            return (Criteria) this;
        }

        public Criteria andVideoWeightEqualTo(Integer value) {
            addCriterion("video_weight =", value, "videoWeight");
            return (Criteria) this;
        }

        public Criteria andVideoWeightNotEqualTo(Integer value) {
            addCriterion("video_weight <>", value, "videoWeight");
            return (Criteria) this;
        }

        public Criteria andVideoWeightGreaterThan(Integer value) {
            addCriterion("video_weight >", value, "videoWeight");
            return (Criteria) this;
        }

        public Criteria andVideoWeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("video_weight >=", value, "videoWeight");
            return (Criteria) this;
        }

        public Criteria andVideoWeightLessThan(Integer value) {
            addCriterion("video_weight <", value, "videoWeight");
            return (Criteria) this;
        }

        public Criteria andVideoWeightLessThanOrEqualTo(Integer value) {
            addCriterion("video_weight <=", value, "videoWeight");
            return (Criteria) this;
        }

        public Criteria andVideoWeightIn(List<Integer> values) {
            addCriterion("video_weight in", values, "videoWeight");
            return (Criteria) this;
        }

        public Criteria andVideoWeightNotIn(List<Integer> values) {
            addCriterion("video_weight not in", values, "videoWeight");
            return (Criteria) this;
        }

        public Criteria andVideoWeightBetween(Integer value1, Integer value2) {
            addCriterion("video_weight between", value1, value2, "videoWeight");
            return (Criteria) this;
        }

        public Criteria andVideoWeightNotBetween(Integer value1, Integer value2) {
            addCriterion("video_weight not between", value1, value2, "videoWeight");
            return (Criteria) this;
        }

        public Criteria andVideoNameIsNull() {
            addCriterion("video_name is null");
            return (Criteria) this;
        }

        public Criteria andVideoNameIsNotNull() {
            addCriterion("video_name is not null");
            return (Criteria) this;
        }

        public Criteria andVideoNameEqualTo(String value) {
            addCriterion("video_name =", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameNotEqualTo(String value) {
            addCriterion("video_name <>", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameGreaterThan(String value) {
            addCriterion("video_name >", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameGreaterThanOrEqualTo(String value) {
            addCriterion("video_name >=", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameLessThan(String value) {
            addCriterion("video_name <", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameLessThanOrEqualTo(String value) {
            addCriterion("video_name <=", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameLike(String value) {
            addCriterion("video_name like", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameNotLike(String value) {
            addCriterion("video_name not like", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameIn(List<String> values) {
            addCriterion("video_name in", values, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameNotIn(List<String> values) {
            addCriterion("video_name not in", values, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameBetween(String value1, String value2) {
            addCriterion("video_name between", value1, value2, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameNotBetween(String value1, String value2) {
            addCriterion("video_name not between", value1, value2, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoLabelIsNull() {
            addCriterion("video_label is null");
            return (Criteria) this;
        }

        public Criteria andVideoLabelIsNotNull() {
            addCriterion("video_label is not null");
            return (Criteria) this;
        }

        public Criteria andVideoLabelEqualTo(String value) {
            addCriterion("video_label =", value, "videoLabel");
            return (Criteria) this;
        }

        public Criteria andVideoLabelNotEqualTo(String value) {
            addCriterion("video_label <>", value, "videoLabel");
            return (Criteria) this;
        }

        public Criteria andVideoLabelGreaterThan(String value) {
            addCriterion("video_label >", value, "videoLabel");
            return (Criteria) this;
        }

        public Criteria andVideoLabelGreaterThanOrEqualTo(String value) {
            addCriterion("video_label >=", value, "videoLabel");
            return (Criteria) this;
        }

        public Criteria andVideoLabelLessThan(String value) {
            addCriterion("video_label <", value, "videoLabel");
            return (Criteria) this;
        }

        public Criteria andVideoLabelLessThanOrEqualTo(String value) {
            addCriterion("video_label <=", value, "videoLabel");
            return (Criteria) this;
        }

        public Criteria andVideoLabelLike(String value) {
            addCriterion("video_label like", value, "videoLabel");
            return (Criteria) this;
        }

        public Criteria andVideoLabelNotLike(String value) {
            addCriterion("video_label not like", value, "videoLabel");
            return (Criteria) this;
        }

        public Criteria andVideoLabelIn(List<String> values) {
            addCriterion("video_label in", values, "videoLabel");
            return (Criteria) this;
        }

        public Criteria andVideoLabelNotIn(List<String> values) {
            addCriterion("video_label not in", values, "videoLabel");
            return (Criteria) this;
        }

        public Criteria andVideoLabelBetween(String value1, String value2) {
            addCriterion("video_label between", value1, value2, "videoLabel");
            return (Criteria) this;
        }

        public Criteria andVideoLabelNotBetween(String value1, String value2) {
            addCriterion("video_label not between", value1, value2, "videoLabel");
            return (Criteria) this;
        }

        public Criteria andVideoInfoIsNull() {
            addCriterion("video_info is null");
            return (Criteria) this;
        }

        public Criteria andVideoInfoIsNotNull() {
            addCriterion("video_info is not null");
            return (Criteria) this;
        }

        public Criteria andVideoInfoEqualTo(String value) {
            addCriterion("video_info =", value, "videoInfo");
            return (Criteria) this;
        }

        public Criteria andVideoInfoNotEqualTo(String value) {
            addCriterion("video_info <>", value, "videoInfo");
            return (Criteria) this;
        }

        public Criteria andVideoInfoGreaterThan(String value) {
            addCriterion("video_info >", value, "videoInfo");
            return (Criteria) this;
        }

        public Criteria andVideoInfoGreaterThanOrEqualTo(String value) {
            addCriterion("video_info >=", value, "videoInfo");
            return (Criteria) this;
        }

        public Criteria andVideoInfoLessThan(String value) {
            addCriterion("video_info <", value, "videoInfo");
            return (Criteria) this;
        }

        public Criteria andVideoInfoLessThanOrEqualTo(String value) {
            addCriterion("video_info <=", value, "videoInfo");
            return (Criteria) this;
        }

        public Criteria andVideoInfoLike(String value) {
            addCriterion("video_info like", value, "videoInfo");
            return (Criteria) this;
        }

        public Criteria andVideoInfoNotLike(String value) {
            addCriterion("video_info not like", value, "videoInfo");
            return (Criteria) this;
        }

        public Criteria andVideoInfoIn(List<String> values) {
            addCriterion("video_info in", values, "videoInfo");
            return (Criteria) this;
        }

        public Criteria andVideoInfoNotIn(List<String> values) {
            addCriterion("video_info not in", values, "videoInfo");
            return (Criteria) this;
        }

        public Criteria andVideoInfoBetween(String value1, String value2) {
            addCriterion("video_info between", value1, value2, "videoInfo");
            return (Criteria) this;
        }

        public Criteria andVideoInfoNotBetween(String value1, String value2) {
            addCriterion("video_info not between", value1, value2, "videoInfo");
            return (Criteria) this;
        }

        public Criteria andVideoThumbnailIsNull() {
            addCriterion("video_thumbnail is null");
            return (Criteria) this;
        }

        public Criteria andVideoThumbnailIsNotNull() {
            addCriterion("video_thumbnail is not null");
            return (Criteria) this;
        }

        public Criteria andVideoThumbnailEqualTo(String value) {
            addCriterion("video_thumbnail =", value, "videoThumbnail");
            return (Criteria) this;
        }

        public Criteria andVideoThumbnailNotEqualTo(String value) {
            addCriterion("video_thumbnail <>", value, "videoThumbnail");
            return (Criteria) this;
        }

        public Criteria andVideoThumbnailGreaterThan(String value) {
            addCriterion("video_thumbnail >", value, "videoThumbnail");
            return (Criteria) this;
        }

        public Criteria andVideoThumbnailGreaterThanOrEqualTo(String value) {
            addCriterion("video_thumbnail >=", value, "videoThumbnail");
            return (Criteria) this;
        }

        public Criteria andVideoThumbnailLessThan(String value) {
            addCriterion("video_thumbnail <", value, "videoThumbnail");
            return (Criteria) this;
        }

        public Criteria andVideoThumbnailLessThanOrEqualTo(String value) {
            addCriterion("video_thumbnail <=", value, "videoThumbnail");
            return (Criteria) this;
        }

        public Criteria andVideoThumbnailLike(String value) {
            addCriterion("video_thumbnail like", value, "videoThumbnail");
            return (Criteria) this;
        }

        public Criteria andVideoThumbnailNotLike(String value) {
            addCriterion("video_thumbnail not like", value, "videoThumbnail");
            return (Criteria) this;
        }

        public Criteria andVideoThumbnailIn(List<String> values) {
            addCriterion("video_thumbnail in", values, "videoThumbnail");
            return (Criteria) this;
        }

        public Criteria andVideoThumbnailNotIn(List<String> values) {
            addCriterion("video_thumbnail not in", values, "videoThumbnail");
            return (Criteria) this;
        }

        public Criteria andVideoThumbnailBetween(String value1, String value2) {
            addCriterion("video_thumbnail between", value1, value2, "videoThumbnail");
            return (Criteria) this;
        }

        public Criteria andVideoThumbnailNotBetween(String value1, String value2) {
            addCriterion("video_thumbnail not between", value1, value2, "videoThumbnail");
            return (Criteria) this;
        }

        public Criteria andVideoUptimeIsNull() {
            addCriterion("video_uptime is null");
            return (Criteria) this;
        }

        public Criteria andVideoUptimeIsNotNull() {
            addCriterion("video_uptime is not null");
            return (Criteria) this;
        }

        public Criteria andVideoUptimeEqualTo(Date value) {
            addCriterion("video_uptime =", value, "videoUptime");
            return (Criteria) this;
        }

        public Criteria andVideoUptimeNotEqualTo(Date value) {
            addCriterion("video_uptime <>", value, "videoUptime");
            return (Criteria) this;
        }

        public Criteria andVideoUptimeGreaterThan(Date value) {
            addCriterion("video_uptime >", value, "videoUptime");
            return (Criteria) this;
        }

        public Criteria andVideoUptimeGreaterThanOrEqualTo(Date value) {
            addCriterion("video_uptime >=", value, "videoUptime");
            return (Criteria) this;
        }

        public Criteria andVideoUptimeLessThan(Date value) {
            addCriterion("video_uptime <", value, "videoUptime");
            return (Criteria) this;
        }

        public Criteria andVideoUptimeLessThanOrEqualTo(Date value) {
            addCriterion("video_uptime <=", value, "videoUptime");
            return (Criteria) this;
        }

        public Criteria andVideoUptimeIn(List<Date> values) {
            addCriterion("video_uptime in", values, "videoUptime");
            return (Criteria) this;
        }

        public Criteria andVideoUptimeNotIn(List<Date> values) {
            addCriterion("video_uptime not in", values, "videoUptime");
            return (Criteria) this;
        }

        public Criteria andVideoUptimeBetween(Date value1, Date value2) {
            addCriterion("video_uptime between", value1, value2, "videoUptime");
            return (Criteria) this;
        }

        public Criteria andVideoUptimeNotBetween(Date value1, Date value2) {
            addCriterion("video_uptime not between", value1, value2, "videoUptime");
            return (Criteria) this;
        }

        public Criteria andVideoTypeIsNull() {
            addCriterion("video_type is null");
            return (Criteria) this;
        }

        public Criteria andVideoTypeIsNotNull() {
            addCriterion("video_type is not null");
            return (Criteria) this;
        }

        public Criteria andVideoTypeEqualTo(String value) {
            addCriterion("video_type =", value, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeNotEqualTo(String value) {
            addCriterion("video_type <>", value, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeGreaterThan(String value) {
            addCriterion("video_type >", value, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeGreaterThanOrEqualTo(String value) {
            addCriterion("video_type >=", value, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeLessThan(String value) {
            addCriterion("video_type <", value, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeLessThanOrEqualTo(String value) {
            addCriterion("video_type <=", value, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeLike(String value) {
            addCriterion("video_type like", value, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeNotLike(String value) {
            addCriterion("video_type not like", value, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeIn(List<String> values) {
            addCriterion("video_type in", values, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeNotIn(List<String> values) {
            addCriterion("video_type not in", values, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeBetween(String value1, String value2) {
            addCriterion("video_type between", value1, value2, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeNotBetween(String value1, String value2) {
            addCriterion("video_type not between", value1, value2, "videoType");
            return (Criteria) this;
        }

        public Criteria andPlaysumIsNull() {
            addCriterion("playsum is null");
            return (Criteria) this;
        }

        public Criteria andPlaysumIsNotNull() {
            addCriterion("playsum is not null");
            return (Criteria) this;
        }

        public Criteria andPlaysumEqualTo(Integer value) {
            addCriterion("playsum =", value, "playsum");
            return (Criteria) this;
        }

        public Criteria andPlaysumNotEqualTo(Integer value) {
            addCriterion("playsum <>", value, "playsum");
            return (Criteria) this;
        }

        public Criteria andPlaysumGreaterThan(Integer value) {
            addCriterion("playsum >", value, "playsum");
            return (Criteria) this;
        }

        public Criteria andPlaysumGreaterThanOrEqualTo(Integer value) {
            addCriterion("playsum >=", value, "playsum");
            return (Criteria) this;
        }

        public Criteria andPlaysumLessThan(Integer value) {
            addCriterion("playsum <", value, "playsum");
            return (Criteria) this;
        }

        public Criteria andPlaysumLessThanOrEqualTo(Integer value) {
            addCriterion("playsum <=", value, "playsum");
            return (Criteria) this;
        }

        public Criteria andPlaysumIn(List<Integer> values) {
            addCriterion("playsum in", values, "playsum");
            return (Criteria) this;
        }

        public Criteria andPlaysumNotIn(List<Integer> values) {
            addCriterion("playsum not in", values, "playsum");
            return (Criteria) this;
        }

        public Criteria andPlaysumBetween(Integer value1, Integer value2) {
            addCriterion("playsum between", value1, value2, "playsum");
            return (Criteria) this;
        }

        public Criteria andPlaysumNotBetween(Integer value1, Integer value2) {
            addCriterion("playsum not between", value1, value2, "playsum");
            return (Criteria) this;
        }

        public Criteria andComentsumIsNull() {
            addCriterion("comentsum is null");
            return (Criteria) this;
        }

        public Criteria andComentsumIsNotNull() {
            addCriterion("comentsum is not null");
            return (Criteria) this;
        }

        public Criteria andComentsumEqualTo(Integer value) {
            addCriterion("comentsum =", value, "comentsum");
            return (Criteria) this;
        }

        public Criteria andComentsumNotEqualTo(Integer value) {
            addCriterion("comentsum <>", value, "comentsum");
            return (Criteria) this;
        }

        public Criteria andComentsumGreaterThan(Integer value) {
            addCriterion("comentsum >", value, "comentsum");
            return (Criteria) this;
        }

        public Criteria andComentsumGreaterThanOrEqualTo(Integer value) {
            addCriterion("comentsum >=", value, "comentsum");
            return (Criteria) this;
        }

        public Criteria andComentsumLessThan(Integer value) {
            addCriterion("comentsum <", value, "comentsum");
            return (Criteria) this;
        }

        public Criteria andComentsumLessThanOrEqualTo(Integer value) {
            addCriterion("comentsum <=", value, "comentsum");
            return (Criteria) this;
        }

        public Criteria andComentsumIn(List<Integer> values) {
            addCriterion("comentsum in", values, "comentsum");
            return (Criteria) this;
        }

        public Criteria andComentsumNotIn(List<Integer> values) {
            addCriterion("comentsum not in", values, "comentsum");
            return (Criteria) this;
        }

        public Criteria andComentsumBetween(Integer value1, Integer value2) {
            addCriterion("comentsum between", value1, value2, "comentsum");
            return (Criteria) this;
        }

        public Criteria andComentsumNotBetween(Integer value1, Integer value2) {
            addCriterion("comentsum not between", value1, value2, "comentsum");
            return (Criteria) this;
        }

        public Criteria andCollectsumIsNull() {
            addCriterion("collectsum is null");
            return (Criteria) this;
        }

        public Criteria andCollectsumIsNotNull() {
            addCriterion("collectsum is not null");
            return (Criteria) this;
        }

        public Criteria andCollectsumEqualTo(Integer value) {
            addCriterion("collectsum =", value, "collectsum");
            return (Criteria) this;
        }

        public Criteria andCollectsumNotEqualTo(Integer value) {
            addCriterion("collectsum <>", value, "collectsum");
            return (Criteria) this;
        }

        public Criteria andCollectsumGreaterThan(Integer value) {
            addCriterion("collectsum >", value, "collectsum");
            return (Criteria) this;
        }

        public Criteria andCollectsumGreaterThanOrEqualTo(Integer value) {
            addCriterion("collectsum >=", value, "collectsum");
            return (Criteria) this;
        }

        public Criteria andCollectsumLessThan(Integer value) {
            addCriterion("collectsum <", value, "collectsum");
            return (Criteria) this;
        }

        public Criteria andCollectsumLessThanOrEqualTo(Integer value) {
            addCriterion("collectsum <=", value, "collectsum");
            return (Criteria) this;
        }

        public Criteria andCollectsumIn(List<Integer> values) {
            addCriterion("collectsum in", values, "collectsum");
            return (Criteria) this;
        }

        public Criteria andCollectsumNotIn(List<Integer> values) {
            addCriterion("collectsum not in", values, "collectsum");
            return (Criteria) this;
        }

        public Criteria andCollectsumBetween(Integer value1, Integer value2) {
            addCriterion("collectsum between", value1, value2, "collectsum");
            return (Criteria) this;
        }

        public Criteria andCollectsumNotBetween(Integer value1, Integer value2) {
            addCriterion("collectsum not between", value1, value2, "collectsum");
            return (Criteria) this;
        }

        public Criteria andSupportsumIsNull() {
            addCriterion("supportsum is null");
            return (Criteria) this;
        }

        public Criteria andSupportsumIsNotNull() {
            addCriterion("supportsum is not null");
            return (Criteria) this;
        }

        public Criteria andSupportsumEqualTo(Integer value) {
            addCriterion("supportsum =", value, "supportsum");
            return (Criteria) this;
        }

        public Criteria andSupportsumNotEqualTo(Integer value) {
            addCriterion("supportsum <>", value, "supportsum");
            return (Criteria) this;
        }

        public Criteria andSupportsumGreaterThan(Integer value) {
            addCriterion("supportsum >", value, "supportsum");
            return (Criteria) this;
        }

        public Criteria andSupportsumGreaterThanOrEqualTo(Integer value) {
            addCriterion("supportsum >=", value, "supportsum");
            return (Criteria) this;
        }

        public Criteria andSupportsumLessThan(Integer value) {
            addCriterion("supportsum <", value, "supportsum");
            return (Criteria) this;
        }

        public Criteria andSupportsumLessThanOrEqualTo(Integer value) {
            addCriterion("supportsum <=", value, "supportsum");
            return (Criteria) this;
        }

        public Criteria andSupportsumIn(List<Integer> values) {
            addCriterion("supportsum in", values, "supportsum");
            return (Criteria) this;
        }

        public Criteria andSupportsumNotIn(List<Integer> values) {
            addCriterion("supportsum not in", values, "supportsum");
            return (Criteria) this;
        }

        public Criteria andSupportsumBetween(Integer value1, Integer value2) {
            addCriterion("supportsum between", value1, value2, "supportsum");
            return (Criteria) this;
        }

        public Criteria andSupportsumNotBetween(Integer value1, Integer value2) {
            addCriterion("supportsum not between", value1, value2, "supportsum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ckplayer_video
     *
     * @mbggenerated do_not_delete_during_merge Fri Dec 21 10:51:00 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ckplayer_video
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}