package com.mrliu.generate.mapper;

import com.mrliu.generate.pojo.AdminInfo;
import com.mrliu.generate.pojo.AdminInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_info
     *
     * @mbggenerated Wed Dec 26 10:29:37 CST 2018
     */
    int countByExample(AdminInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_info
     *
     * @mbggenerated Wed Dec 26 10:29:37 CST 2018
     */
    int deleteByExample(AdminInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_info
     *
     * @mbggenerated Wed Dec 26 10:29:37 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_info
     *
     * @mbggenerated Wed Dec 26 10:29:37 CST 2018
     */
    int insert(AdminInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_info
     *
     * @mbggenerated Wed Dec 26 10:29:37 CST 2018
     */
    int insertSelective(AdminInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_info
     *
     * @mbggenerated Wed Dec 26 10:29:37 CST 2018
     */
    List<AdminInfo> selectByExample(AdminInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_info
     *
     * @mbggenerated Wed Dec 26 10:29:37 CST 2018
     */
    AdminInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_info
     *
     * @mbggenerated Wed Dec 26 10:29:37 CST 2018
     */
    int updateByExampleSelective(@Param("record") AdminInfo record, @Param("example") AdminInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_info
     *
     * @mbggenerated Wed Dec 26 10:29:37 CST 2018
     */
    int updateByExample(@Param("record") AdminInfo record, @Param("example") AdminInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_info
     *
     * @mbggenerated Wed Dec 26 10:29:37 CST 2018
     */
    int updateByPrimaryKeySelective(AdminInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_info
     *
     * @mbggenerated Wed Dec 26 10:29:37 CST 2018
     */
    int updateByPrimaryKey(AdminInfo record);
}