package com.mrliu.generate.mapper;

import com.mrliu.generate.pojo.Video;
import com.mrliu.generate.pojo.VideoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ckplayer_video
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    int countByExample(VideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ckplayer_video
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    int deleteByExample(VideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ckplayer_video
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    int deleteByPrimaryKey(Integer videoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ckplayer_video
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    int insert(Video record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ckplayer_video
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    int insertSelective(Video record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ckplayer_video
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    List<Video> selectByExample(VideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ckplayer_video
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    Video selectByPrimaryKey(Integer videoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ckplayer_video
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    int updateByExampleSelective(@Param("record") Video record, @Param("example") VideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ckplayer_video
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    int updateByExample(@Param("record") Video record, @Param("example") VideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ckplayer_video
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    int updateByPrimaryKeySelective(Video record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ckplayer_video
     *
     * @mbggenerated Fri Dec 21 10:51:00 CST 2018
     */
    int updateByPrimaryKey(Video record);
}